version: "3.6"
services:
  elastic:
    image: bakingbad/bcdhub-elastic:3.4
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"

  mq:
    image: rabbitmq:latest
    restart: always
    volumes:
      - mqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging: *my-logging

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
    volumes:
      - db:/var/lib/postgresql/data
    logging: *my-logging

  api:
    restart: always
    image: bakingbad/bcdhub-api:3.4
    environment:
      - BCD_ENV=${BCD_ENV:-sandbox}
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://flextesa:20000
      - SANDBOX_IPFS_GATEWAY=https://ipfs.io
    depends_on:
      - elastic
      - db
      - mq
    ports:
      - 127.0.0.1:14000:14000
    logging: *my-logging

  indexer:
    restart: always
    image: bakingbad/bcdhub-indexer:3.4
    environment:
      - BCD_ENV=${BCD_ENV:-sandbox}
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://flextesa:20000
      - SANDBOX_IPFS_GATEWAY=https://ipfs.io
    depends_on:
      - elastic
      - mq
      - metrics
    logging: *my-logging

  metrics:
    restart: always
    image: bakingbad/bcdhub-metrics:3.4
    environment:
      - BCD_ENV=${BCD_ENV:-sandbox}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://flextesa:20000
      - SANDBOX_IPFS_GATEWAY=https://ipfs.io
    depends_on:
      - elastic
      - mq
      - db
    logging: *my-logging

  flextesa:
    restart: always
    image: trufflesuite/flextesa-mini-archive
    command: edobox start
    environment:
      - block_time=4
      - flextesa_node_cors_origin=*
    ports:
      - 127.0.0.1:8732:20000
    logging: *my-logging

  gui:
    container_name: sandbox-gui
    restart: always
    image: bakingbad/bcdhub-gui:3.4
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
    logging: *my-logging

volumes:
  esdata:
  mqdata:
  db:
    driver: local